#pragma GCC optimize("Ofast,unroll-loops")
#pragma GCC target("avx,avx2,fma") 
#include <bits/stdc++.h>
using namespace std;

unordered_set<string> result;
const int F = 0, U = 1, T = 2;
const int AND = 0, OR = 1, IMP = 2, EQU = 3;
const string andtable = "FFFFUUFUT", ortable = "FUTUUTTTT", imptable = "TTTUTTFUT", equtable = "TFFFTFFFT";
int val(char ch) {
    if (ch == 'F') return F;
    if (ch == 'T') return T;
    return U;
}

int idx(int lit1, int lit2) {
    return lit1 * 3 + lit2;
}

string getresult(string &table1, string &table2, int op) {
    string ret = ""; 
    int i;
    if (op == AND) {
        for (i = 0 ; i < 9; ++i) {
            int i1 = val(table1[i]), i2 = val(table2[i]);
            ret += andtable[idx(i1, i2)];
        }
    } else if (op == OR) {
        for (i = 0 ; i < 9; ++i) {
            int i1 = val(table1[i]), i2 = val(table2[i]);
            ret += ortable[idx(i1, i2)];
        }
    } else if (op == IMP) {
        for (i = 0 ; i < 9; ++i) {
            int i1 = val(table1[i]), i2 = val(table2[i]);
            ret += imptable[idx(i1, i2)];
        }
    } else {
        for (i = 0 ; i < 9; ++i) {
            int i1 = val(table1[i]), i2 = val(table2[i]);
            ret += equtable[idx(i1, i2)];
        }
    }

    return ret;
}

void init() {
    result.insert("FFFUUUTTT");
    result.insert("FUTFUTFUT");
    vector<string> curr;
    int idx = 1, i, j;
    //bool ok = true;
    for (auto s : result) curr.push_back(s);
    while (idx < (int) curr.size()) {
        //ok = false;
        unordered_set<string> newly;
        for (i = 0; i < (int) curr.size(); ++i) {
            for (j = 0; j < 4; ++j) {
                string ret = getresult(curr[i], curr[idx], j);
                if (result.find(ret) == result.end()) {
                    newly.insert(ret);
                }

                ret = getresult(curr[idx], curr[i], j);
                if (result.find(ret) == result.end()) {
                    newly.insert(ret);
                }
            }
        }

        // ok = (int) newly.size() > 0;
        idx++;
        for (auto &ss : newly) {
            result.insert(ss);
            curr.push_back(ss);
        }
    }
    
    i = 1;
    for (auto ss : result) {
        if (i == 0) {
           cout << endl;
        }
        cout << "\"" << ss << "\",";
        i = i + 1;
        i %= 100;
    }
}

string ss[1944] = {
"TTFFTTTUT","TTFFFTTUT","FTFFFTTUT","TTFUFUFTT","TFTFTUFTT","TFTUFUFTT","FFTFFUFTT","TUTFFUTFT","TFFFUUFTT","TTFUFUTFT","TUFUFUFTT","TFFUFUTFT","FFTUFUFTT","TFTTUUTFT","FTFFTUFTT","TFTTUUFTT","TFFFUUTFT","FFTUFUTFT","TFTTFUFTT","TFTFUUTFT","FFTTFUFTT","TFTFFUFTT","TFFTFUTFT","TFTTFUTFT","TFFFTUFTT","TTFTFUTFT","FTTFFUTFT","TTFFFUTUT","TFFFFUFTT","TTTFFUFTT","TFTFTUTFT","TTTFFUTFT","FUTUFUTFT","FFTTFUTFT","TUFTFUTFT","FUTTFUFTT","FTTUFUTFT","TTTFTUTFT","TTFTFUFTT","TFTFUUFTT","TFTUFUTFT","TUFFFUTFT","TUFFFUFTT","TUFUFUTFT","TUTUFUTFT","FUTTFUTFT","TUFTFUFTT","FTTUFUFTT","TUTTFUTFT","TUTFFUFTT","FTFUTUFTT","FTFUTUTFT","TUTFUUTFT","FTFTTUTFT","TUTFUUFTT","FTTTUUTFT","TTTUFFTFT","TUFUFTFTT","FTFTUUFTT","TFTUFUFUT","TUFTFTFUT","TFFTFTFUT","FTTTUFFUT","TUFUFTTFT","TUTUFFFTT","FUFTFUTFT","TFFTFUFUT","FUFTFUFTT","FFFTUUFTT","FFTTUFFUT","TTTUFFFTT","TFFUFTFTT","FTTTTUFTT","FFFTUUTFT","FTFTFTFUT","FFTTFFFUT","TTTTFFFUT","FFTTFUFUT","FFFTFUTFT","TTFUFFTFT","FUFTFTFUT","TFFUFTTFT","FUTTFFFUT","TTFUFTFTT","TFTUFFFTT","FFFTFUFUT","FUFTTUTFT","FUTUTUFTT","FUTTTUFTT","TUTFTUFTT","FFTUTUFTT","FFFTTUFTT","FTTTFFFUT","FFTTUUFTT","FTFUTTTFT","TUFFTTTUT","FFTUTUTFT","FFTTUUFUT","FUTTTUTFT",
"TUTFTUTFT","FFTUTTFTT","FTFUTUTUT","FTTUTUTFT","FUFFTUTFT","TFTTTUTFT","FFTUUUFTT","FUTUTFFTT","FFTUUUTFT","FFTFUUTFT","FTTUTFFTT","FFTTTUFTT","FUTFFUFTT","FUFFTUTUT","FFFFTUTFT","FUFUTUFTT","FFFUTUTFT","FTFUTFTFT","FFFFTFTUT","FTTUTFTFT","FUTUTFTFT","FFTFTTTUT","FTFFTFTUT","FFTUTFFTT","FTTTUFTFT","FTTTUFTUT","FFTTUUTFT","TFTTTUFTT","FFFTTUTUT","FUTFTFTUT","FTTTUFFTT","FFFUTUFTT","FFTTTUTUT","FFTUTUTUT","FTFUTFFTT","FFTFUUFTT","FFFUTFTFT","TFFFUTTFT","FTFUTTFTT","FFTFTUFTT","FFTTTFTUT","TFFFFUTFT","FFTTTUTFT","FFFUTFTTT","TTFUUTTTT","TFTTUTTTT","FFFFTTTTT","FTFFTTFTT","TTTUUUFFT","FUFTFFTFT","TTFUUFTTT","FUTFTTTTT","TUTFTUTUT","FFTTFUFFT","TUTFFFTTT","FUFTTUFTT","FTTTTTFTT","TFFTTFTFT","FTFFUUTTT","FUFFFTFTT","TFTTTUFUT","TTTTUUTTT","TTFFFFFFT","FFFTTFTUT","FTTUTFTTT","FTFUUTFTT","FFFFUFTTT","FUFTFUFFT","FUFFFFFTT","FFTFUFTTT","TUTTUFTFT","FUTUFFFUT","FFTFFUTTT","TTFTUUTFT","TUFFFFTTT","TFTTFUTTT","FTFFUFTTT","FFTUFTTUT","TFFUUFTTT","FFFFFFTUT","TFFUUTTTT","TFFUTUTUT","FTFFUTTTT","TFFFTUTFT","TFTUFTTTT","FTFUTFTUT","TUFTFTFTT","FUFUTTTTT","TTFTTFFFT","FUFFTTTTT","TUFFUFTTT","FTTFTTFFT","TUTTUFTTT","TFTFFTTTT","FFFFFFTFT","FUTUUFTFT","TUFFUFTFT","TTFTTFFTT","TFTUFTTUT","TTFFTFFTT",
"FUFFTFFTT","FUTUFFFTT","TTTUFTFTT","FTFFFTFTT","FUFTUFTFT","FTFTTFFFT","TUFFTTTTT","TTFFUTFUT","FFTTFTFTT","FFTTTFTTT","FUTUFUFTT","FTTFTTTUT","FTTTTTTFT","TFTFTTFTT","FFFFFUFUT","FUTTFUFUT","TTFTFTFUT","FUFUFTFFT","TTFFUTFFT","FUTUFTFFT","TTFFUUFFT","FFFTTTFTT","TTFFTFTUT","FUFFFUFFT","FTFTTFTTT","FFTFTUTUT","FFTTTFFTT","TTTFTUFFT","FFFTTFFTT","FFTTUFTFT","FFTFTUFFT","TFFTUFTTT","FTTFUUTFT","TFFFUUTTT","TTFTTFTFT","TFTUUFTUT","FFFTFFFTT","FUFTTFFUT","TUTUTTTUT","FUFUTFTTT","FFFFTUFFT","FUTTFFTTT","TFTTFFFTT","TUTTFFTTT","TUTTFTTTT","FFTTFFFTT","FTTUUFFUT","TFTFFFFTT","FTFFUTFFT","FUTFFUFUT","TFTFFTTUT","TFFTFUTTT","FTTFTFFFT","TUFFUUTTT","FFFFUTFFT","TTFFTUFFT","TTFFUFTTT","TUFUTUFFT","TFTUUUTUT","TUTFFUFFT","FTTFTUFFT","FFTFUUFFT","TFTFUTFFT","TFTTTTFTT","TFTUUTTTT","TFFTFTTUT","FTFFTFFFT","FUTUUFTTT","FTFUFTTTT","TTTUFTFUT","FTTTTTTUT","TFTUUUTTT","TUTFUUTUT","TFTTTFTTT","TFFUTTTUT","FTFUUUFUT","FUTFFUTFT","TFTUFTFTT","FUFUTTFUT","TFFUTTFFT","FUTUFTTFT","TUFTUFTTT","TTFUUTTUT","TFFUFUFTT","TTFUTFTUT","FUFTTUFUT","FTTUFTTUT","FUTTUTFFT","FTFUFUFTT","TFTFTTTFT","TTTTFTTUT","FUTTFFFFT","TTFFFFTUT","TTTFFTFFT","FUFFUFFUT","FFFUUFTFT","TFFUTTFUT","TFFTFTFFT","TTTUFTTTT","TTFTFTFFT",
"TFFUUTFTT","TFTUTTTUT","FTFTTTFFT","TUTTTUTTT","FUFUUUFFT","FUTUTTTUT","TUFFTTFFT","FFFUUFFUT","TTTUTTTFT","FUFFFFFFT","FTTUUTFTT","TTFTUFFFT","FUTTUUFFT","TTTUTFFUT","FTTUUUFUT","TUTTFFFUT","FFFFFTTTT","TFTUFTFUT","TTFTFFTUT","TTTFFUTTT","FTFFFTFFT","FUFUFUTTT","FTFFUUFFT","FUTUTTFFT","TFFFFFFUT","FTTUTTFFT","FTFUFTFUT","FTTFTTTFT","TTFFTUFUT","FUTTUFTFT","TFFUFFFFT","TFFUUTFUT","TUTFFFTUT","FTFUFFFFT","FUTFFFTUT","TTTTTFFTT","FFTUUFTTT","TTFUTUFUT","FTTFUTFTT","TTFTFTTFT","FTTTFTTUT","FFTUFFFFT","TTFUTFTFT","TFTFTTFFT","TTFFTTTFT","TUTTTTTUT","TFTFTFTUT","TFTFFTTFT","TFFFTUTUT","TFFUFTFFT","FTTUFTFUT","FUTFUTFTT","TTTFUTTFT","TUFFTTFTT","TFFUUUFUT","TTFUTFTTT","TFTUTFFUT","FUTTUUTTT","FUTUUUFUT","TTFTFFFFT","FTFFFFFUT","FUFFUUTTT","TTTUFUTUT","FFFUFFFFT","FTFFFUTTT","TFFFTFFUT","FFTUFUTTT","TTFTTFTUT","TTTFTFFTT","TTTFFFTFT","FFTTUTFUT","TUFUTFFUT","TFFUTFFUT","TUFUUFFUT","FUFUTFTFT","FUFFFUTTT","FFTUFTFFT","FUTUTTFUT","TFTTUFTTT","FFTUTTTUT","FUFFUTTFT","FFTFUTFUT","TUFTUFTUT","TUFFFFFFT","FUTUFTTUT","TTFUFFFUT","FUTFTTFFT","FUFUFUFUT","FFTUFTTTT","FUTFTTTFT","FTFUUUTTT","FFFTTTFFT","FFTTFUTUT","FTFUUFFFT","FTTTTFTUT","FUTTFTFFT","FUFUFTFUT","TUTFTFFUT","FTFFFUFTT","TUFFTFTFT",
"FTTFFUFUT","TTTTUTTTT","TTTFTFFUT","TTFFTFFUT","FTFFUFFUT","TFFUFFTUT","FTFTUTTUT","TFTTTFTFT","FTTUFFTTT","TFFTTFTTT","FFTFFFFFT","TTFUTTTFT","FFTTTFFFT","TUTTFTFFT","FFTUFFTUT","FTFUUTFUT","TFFTTTTUT","TUFUTFFFT","FFFUFUFFT","TFFFFTFUT","FFTUTTTFT","TUTFUTFFT","TTFTUUTTT","FUFFFUFUT","FTFFTUTUT","TTTFUTFUT","FUTUTTTFT","FUFUFUTFT","FFTFFTFUT","FTFTFUTTT","TFTTUUFFT","FFTUUUTTT","FFTFFFFUT","FTTUFTTTT","FFTTFUTTT","FFFUFFTTT","TTTUFFTUT","FUFUFUFFT","TTTUTTFTT","TFTFTFFTT","TFTFFFFUT","FTTTTFTTT","FUTFTFTTT","TTTFFFFUT","TTFFFTFFT","FFFTUUFUT","TUFUFFTFT","TTFUFFFFT","TUTFTUFUT","FFTFFFTUT","FTFUFFTTT","TFFTTTTTT","TTFFUTTTT","TUTTTFFUT","FUTTFTTUT","TTTTTFFFT","TTTTFFTUT","FUTUFTTTT","TFTUTUTUT","TUFTUUTFT","FUFUUUTUT","FUTUFTFTT","FUTTTFFUT","TUTTUTTUT","FTFTUUTUT","FTTUFUTTT","FUTTTFTTT","FUTUFUTTT","FUTUUTTUT","TFTUTTFUT","TTTUFFFUT","FFTFTFTTT","FTTTFTFTT","TUTUFTTTT","TFFUFUTTT","FTTFFTFTT","FUFFUFFFT","TFFFUUFFT","FFFFFTFFT","FTFUFFTUT","FTTTUUTUT","FTTFFTFUT","FFFTUFFFT","FUFTUFTTT","TUTUTTFUT","FTTTUFTTT","FFTUTTTTT","FFFTFTTUT","TFFFUTTTT","FUTFTUFFT","FTFFTUFFT","TTFUFTTFT","TTTFUUTUT","TTFTFTFTT","TTFFFFFUT","FUFTUUTUT","FTTTTFFFT","TFFUUUTTT","FTFUUUFFT","TFFUFTFUT",
"FFFUUUTUT","FFFUFTTUT","TUFFFFTFT","TFTUTUFUT","FTFFUUTFT","FFTUTUTTT","TUTTUTFTT","TFFUTTTTT","FFFTTFFFT","TTFFFTTTT","FFFFFUFTT","TTFFFTFUT","FTTUTUTUT","FTFUTTFUT","FTFTUFTUT","FUFUUUFTT","FFTFFFTTT","TFFFFUFUT","TTFUTTFUT","TTTFFTFTT","FTFFTFTTT","TFTUUUFFT","FUFFFFFUT","TTFFFTTFT","TUFTFTTUT","FFFUUFTUT","FTFFTTTTT","TTFTTTFTT","FTTUTTFUT","FTTUTFFFT","TUFTUUTTT","FUFUFTTFT","TTTUFTFFT","TTTUTFFFT","TTTUTTTUT","TTFUTFFUT","TUTTTTFUT","FUTTTTTTT","TFFFTFTUT","TFTTFFFFT","FTTFUUTUT","FUFFUTFFT","TUTFTTTTT","TFFUTFFFT","FTTTTUTTT","FTTFFTFFT","TUTFTTFUT","TFTUUTTUT","FTTFFFFUT","FUTUTUTUT","TFTTUTFUT","FTTUTUTTT","TFTFTUFFT","TUTUTUTUT","FUFFFTTTT","TFTTTTFUT","TTTTFTFFT","TTTFUFTTT","TFTFFTFTT","TTFTTTFFT","FUFFTUFTT","TUTUUTFFT","TFFUFFTTT","TUFUUFFFT","TFFUTUTTT","TFFFFFTFT","TFTUTTFFT","FTTUUUFFT","TUFTTFFFT","FUTFUUFFT","FTTTFFTFT","FFTTUTFFT","TTFFFUFFT","FUTUUUTFT","FFTUUUFUT","FTTFFUTUT","FUTFUUTTT","TFTTFTFFT","TTTFUUFUT","TTFTTTTUT","FTTTFTFFT","FTTUFFFUT","TFFFTTTTT","TTTFUFFTT","TFFFFTTFT","FTFTFTFFT","FFTFTFFUT","TUTUTUFTT","FFTTFTTFT","TTTFUTFTT","FTTTFUTFT","TUTUTUFUT","TFFFUFTTT","FTFFFFTUT","TFTFUUFUT","FFFUFUTUT","FFFUTFTUT","TUFUTFTTT","TUTFFTTTT","TTTUTUTTT",
"TFTUUUTFT","FFTFUFFFT","TTTFTUFUT","FFFUFFFUT","FTTTUUTTT","TUTFTTFFT","FFFUFUTTT","TTTTFUFFT","FUFTUTTTT","FUFUUTFUT","TTFFTFFFT","TTTTUUFFT","FTFTFTTFT","FUTFUTFFT","TFTFUTTTT","FTFTFFTUT","FFTUFFTTT","FFTUUTFUT","FUTUUTFTT","FFTTFFTTT","TFFFTUTTT","FTTFTTTTT","TTTTTUFFT","TFTUTUFTT","FTTTFFFFT","TTFFUTTFT","FUFFFUTFT","TTFFTTFFT","FTFUTUFUT","FTTFFFTFT","TUTUFTFFT","TUTFFTFUT","TUTUFUTUT","FFFTTFTTT","FUFFUUTFT","TUTFUFFTT","TTTTFFTTT","TUFUTTTTT","FTFFFFFTT","TTTFTTFUT","TTFUTUTTT","FTTUUTTUT","TTFTFUTUT","TTFUFUTTT","TTFUTTFFT","FUTTTTFTT","FFTTTFTFT","TUFUUTFUT","FFFTFFFFT","TFTTFTTTT","FUTUUUTUT","TTFFFFTTT","FTTFFFTTT","FUTFUUFUT","FUTFUFFUT","FFTTTTTFT","TUTFFUTTT","TUFFUTTUT","FTFUUTTTT","FFFTTUTTT","FUTUTUFUT","TFFUFFFUT","TUFUTUFUT","TFTFTUFUT","TFTTTTFFT","FFFFTTFFT","TFTFFTFUT","FUTUUTTTT","FFFUUTFUT","FFTTFTTUT","FUTUTTFTT","TFFTUTTTT","FTTUFFFFT","TUFFUUFFT","TFTTTUTTT","TUFTFFFUT","TTTUTUFFT","TUFFUFFFT","TTFFTFTTT","FTFTFFTTT","FFFTUUTUT","TUTTTTTTT","FFTFFFFTT","FTFFFFTTT","TTFTTUTTT","TTTTTFTTT","FTFTUUFFT","FUTTFUTTT","FFFFFFFFT","FTFTTFFTT","FUFFTUTTT","FUFFTUFUT","FTTUFTFFT","FFFFFFFUT","TTTUTTTTT","TFFTTFFTT","TUTFFTFFT","FFTFFUFUT","TUFUTUTUT","FFFFUUFTT",
"TUFUUFTUT","FFFFFTFTT","TUFTUTFTT","TFTFFUTTT","TUFTTUTTT","FFFUFTTTT","TTTTTUTUT","FTTTUTFFT","FUFUFFFUT","FUFUUUFUT","TUTUUTTTT","TFTFTUTTT","TTTFFTTFT","TFTUUTFUT","TFFFFTFTT","TUFFTFTTT","TUFTTUFFT","FUFUUUTTT","TFFTFFFTT","FTFUFFFUT","FTTTFTTTT","FTTFTFTTT","TFFTFFFFT","TFFTFTFTT","FUFTUUTTT","TFTUTTTTT","TUFUTFTUT","FUTFFFTTT","FFTTFTTTT","TTFFFFTFT","FUTTUTTTT","TUTUUTFUT","FFFTFUFFT","FTTTFFFTT","FTFFTTTFT","TUFFFTFUT","TTTUUFFTT","TTFTFFTTT","FUTUFFTUT","TUTUUFTTT","FFFFFFTTT","FTFUTFFUT","TTTFUUTTT","FTFTFTFTT","TTTFTTFFT","TFFFTTTFT","TTTTFTTTT","FFFFUUFUT","TUTFTUFFT","TFFFFFTTT","FFTFFTFFT","TUTFTFTFT","FUTFUFFTT","FUTTUTFUT","TTTUFFTTT","FUFTFTFFT","TFFTUUTFT","FTTFFTTTT","FFFFUTTFT","FFTUFFFUT","TTFTTUTFT","FUTFTUTFT","TTTTFTFTT","FUFUUFTTT","FUTFUTFUT","FFTFUUTTT","TFTUUFTTT","FTFFUTTFT","TFTTTTTTT","TTTFUTFFT","TFFFTUFFT","FUFFTTFFT","TFTTFFTUT","TUTUFTTUT","FTTUFUFFT","FFFTFFTFT","TUFTUUTUT","TTFTUTTTT","FUFUTUTFT","TFFUTTTFT","TUTFTTTUT","TUFUFTFFT","TTFFFFFTT","TUFTTFTTT","FFFUUUTTT","TFFFTFFFT","TFFFTTTUT","TFFTUTTUT","TTTFUFFFT","TTTUTTFFT","FUFUTUFUT","FTFFFUTFT","FFTTTTFFT","TTFUUUTTT","TTTFTUTTT","TTFTTTFUT","FUFTUTFFT","FTFTUFTTT","TTTFUTTUT","FFFUUFTTT",
"TTTUTTFUT","TTFFTTFTT","TFTTUUTTT","TUTUFUTTT","TTFUFTFUT","FFFUTUFUT","TFTFTTTTT","TUFTTUFUT","FFFTFUTTT","TTTFFFTTT","FTTUTUFUT","TTTTTTTTT","FUTFFFFUT","FTTFTFTUT","TTTTTTFUT","FFFUFFTUT","TUTFUUTTT","FUTUUUTTT","FTTFFUTTT","FUTTFFTFT","FFTUTFTUT","TTFTUUFFT","FFTFTTFFT","FTFFTFTFT","TFTFTFFFT","TFTTFUFFT","TFTFFFTTT","TFTUTUTTT","FFFTFUTUT","FUTFFUTTT","FTFTTUTTT","TTFTTTTTT","TFFFTFTFT","TTTTTUFTT","FTTUUTTTT","TUTFFTTUT","FTFTFFFUT","FTFTFFTFT","FUFFFFTTT","FFFTTUFUT","TUTFUFTUT","TUTUTTFFT","FFTFTTTTT","FTFTTUTUT","TFTTFFTFT","TFFTUUFUT","FUFFUUFUT","FTTUTFFUT","TTFFFUTTT","TUFUFFFFT","TFFUFUTUT","FFFTUTFUT","TUTTTTFFT","TTFFTTFUT","FTTFUUFFT","TTTFTFTTT","FFTFUTFFT","TTFFUTTUT","FUFFFTFFT","FTTTUTFTT","FTTUFFTUT","TUTFTTTFT","TFFFFUTTT","FTFTFUFTT","TUFTTTFUT","TUFTUTFFT","FTFTFFFFT","FUTUUFFTT","FTTFUTFUT","TUTTUUTUT","FTTUFTFTT","TFFFUFFFT","FTTUUTFUT","TUFUUFFTT","TUTUTFFTT","TFFTFFTFT","TFFTTUFUT","FUTUUTFUT","FTTFFUFTT","TFTUTFTUT","FFFFTUTUT","TTTUTFTUT","FFTFUUFUT","TFTFUTFUT","TTFUTFFFT","FUFFTFTFT","FTFTTTFUT","TFFFTFTTT","FUFFUTFTT","FTTTFFTTT","FUTFUFFFT","FUTUFFTTT","FTTTUUFUT","FTTFUFTTT","FUTFFTTTT","TUFTTFTUT","FFTFTTFUT","FFFTUTFFT","TFTTFTTUT","FFTUUUTUT",
"TTTTUFTTT","FUFTTFTTT","FFTUUTTFT","FFTFTTTFT","TFTUFFTTT","TFFFUFFUT","TFTTTFFTT","TTTTTFTFT","FUFTTTTTT","FTTFTTFUT","TFFFFFTUT","FFFTTUTFT","FFTFFFTFT","FTFTUFTFT","FTTTUTFUT","FTFTUTTTT","FFTFTFFFT","TFFUTFFTT","TTFFTUTUT","TTTFTUFTT","TFTFUUTTT","TFTTTUFFT","FTFFFTFUT","FUTTUUFTT","TUFFTUTTT","FTTFUFFUT","FUTUTUFFT","FUFTUTTUT","TUTUTFFFT","FTFTUUTTT","TTTFTTFTT","TFTTTTTUT","FFFFUTFUT","TFFTUUTUT","FFFFTFFTT","TUTUUFTUT","TFFFTUFUT","TUFUTTFUT","TTTFFFFFT","TUFUUFTFT","FFTUUTFTT","FTFFUUFUT","TTTTFUTTT","FUFFUUFFT","FTFTTFTFT","TFTFTUTUT","TUFFTTFUT","FTFTTTTTT","TTTTFUTFT","TUTTFFFTT","FFFTTTTTT","FTFFUFTFT","FTFUFUTTT","TFTTUTFTT","TFFTTTFFT","TUFUUTFTT","TTTUUTFFT","FUFTUTFUT","TFFUUFTUT","TUTFTUTTT","FFTFUFTFT","TTTTTUTTT","FTFTTFTUT","TTTTTTFFT","TFTTTTTFT","TFTFUUFFT","TFTUTFFTT","TUFTTTTTT","FFFFUUFFT","TFTFUFTTT","FUFUFFTUT","FFTFFTTTT","TTTFFTTTT","FFFTFTTTT","FTTUFUTUT","FFTUUUFFT","TTTUFUFUT","FUTTUUFUT","FTTFUTFFT","FUFTFUTTT","FFFFUUTUT","FFTTUTTFT","TUFFTUFUT","TFFTFTTFT","TFTFUTTFT","TFFTFFTTT","FFFUUUFUT","TUFUTFTFT","TUFFFUTUT","TTFTFTTUT","FUFTUUTFT","FTFUTUTTT","TUTUFFTUT","FUFUTUTTT","TTTTTUFUT","FFTFFUFFT","FFFFTTTFT","TFFFUTFFT","TFFUUUTUT","TFTFFUTFT",
"TTFTUTFUT","TTFFUUFUT","FFFUTTFUT","TFTFFTFFT","FUTTTUFFT","FTTFUUTTT","TFFTFFTUT","FUFTTTFUT","TFTUFTFFT","FTFTTUFUT","FFTTUFFTT","TTFUUFFTT","FUTUTTTTT","TFTTFFFUT","TFFUUFFTT","TTTFTFFFT","FTFTFTTUT","FTFTUTFTT","TTTFFFFTT","FTFUUTFFT","TFFUTUFUT","FFFTFUFTT","FTTFTTFTT","FUFFTUFFT","FFFFTFTFT","TTFFUUTTT","FUTFFFTFT","FUFTTFTFT","TUTFUUFUT","FTTTTTFUT","FFTFFTTFT","TUTUTTFTT","TFTTFFTTT","FFFFFUTTT","FFTUUTTTT","FUTTUFFFT","TTTTFFFFT","FFTUUFFFT","TTFFUFTUT","FTFFTFFTT","TTFFTFTFT","TFTUUFFUT","TTTUUTFUT","FFFFFTFUT","TUTTUUFTT","TTFUUTFUT","FTTUTTTFT","TFTUFFTUT","FTFFFFTFT","FFTFUTTTT","FTFUFUTFT","TFTFUFFUT","FFFTTTFUT","FTTTTFTFT","FFTTUFTTT","TTTTFTTFT","TTFTTFFUT","FUFTUFFFT","FUFTTUTUT","FFFUTUTTT","FUFTUFFTT","TUTFFUTUT","TTTUTUFUT","TTTTFFTFT","TFFUUUFFT","TFTUUTTFT","FFFUUTTTT","FFFTTFTFT","TFTTUTTFT","TTTTFUFUT","FFFFFFFTT","FFFFFTTFT","TTTUFUTTT","FFTTTTFUT","TTTUTFTTT","FFTFFTTUT","TTFUFFTTT","TFFTUFFTT","FUTUFUFUT","TUFUTTFTT","FFFTFTFFT","FTTFTUTTT","TTFTTTTFT","TUTUTUTTT","FUFTUTFTT","FFFTFTFTT","TFFFUTFUT","TUFTFUTUT","FTTFTFTFT","TUTTFTTUT","FFFUTFFTT","TUFUUUTTT","TFFFFTTTT","TFFFUTFTT","FTTTTFFTT","FUFTTFFTT","FUFTUUFUT","TFTTTFTUT","TTTFTTTFT","FFTTUUTTT",
"TTTTUUFUT","TUTTFUFTT","TTFFTTTTT","TFFFFFFTT","TUFTUTTFT","FFFFUTTTT","TUTFUTTTT","TFFTFUTUT","FTFFUTFUT","FUFFUTFUT","TUTTUUTTT","FTTTTTTTT","TUTUUTTFT","TFFUTUFTT","FFTFUUTUT","TFTFTFTTT","TTFUTTTTT","FFFTUFTTT","FFTFFUTFT","TTTTUTTUT","FTFFTUTTT","FFFUTTTUT","FFFFTTFUT","FTTFFTTFT","FFTTUTTTT","TUFFTFFFT","FUFFFFTUT","FFFFUTFTT","TFFFTTFUT","TUTUFFFUT","TTTFUUTFT","FUTFFTFTT","FTTFFFFTT","TUTFUUFFT","FFTTTFFUT","FUFUUTFTT","FUFFUTTTT","FTFTUFFFT","TTTFTTTUT","FFFFTUFUT","TFFTUUTTT","FFFTFTTFT","TTTFFTTUT","TFFUTUTFT","TFTFUFFTT","TUFTTUTUT","TUFUTUTTT","TUTUFTTFT","TUTFFUFUT","FUFUFFFFT","TFFUTUFFT","FUFFUFTFT","TFTUUUFUT","FFTTFFTFT","TUTTUTTTT","TTTTUTFUT","TTFUTTTUT","TFFTUTTFT","TTFTTUFUT","FFFUFTFFT","TTTTTTTFT","FFFFTFTTT","TFFTTUFTT","FTFTTTTFT","TUFUTUTFT","FUFFUFTTT","FTFUTFTTT","TTFUFTTTT","TFFTTUTFT","FFTUTFTTT","TUFUFFTTT","TUFTFTTTT","TTTFUTTTT","TTTUFUTFT","TFFTTTTFT","FTFTUTFUT","FTTUUFTTT","FFTUFTTFT","FTFFFTTTT","FTFUUFTTT","TUTUFFTTT","TTTTUFTFT","TFFTUTFUT","TTFFUFFUT","TFFTUUFTT","FUFFTFTTT","TFTFTFFUT","FUFTTUTTT","FFTTUUTUT","FFFFTTFTT","TFFTTFFFT","FUFUFFTFT","TFFUTFTTT","FTFTTTFTT","TTFFFTFTT","FTTUUUTFT","FFTFTFFTT","TFFTUTFFT","TTFTUFTTT","FTTFFTTUT",
"FFTUTFFFT","TUFUUFTTT","TUFTFFTTT","TTTTUUTFT","FFTUFTFTT","FFTFTUFUT","FFTTFTFUT","TUTTFUFUT","TFFFTTFFT","TUFFFTFTT","FFTTTUFUT","FUTTTTTUT","FUTTUTTUT","FFFUFFTFT","FFTUTTFFT","TTTFFTFUT","FTTUUTFFT","TUFFTUTFT","TFFFFUFFT","FFTFUTFTT","TTTUUTTUT","FTTFUTTUT","FUTUFTFUT","TFTFFUFFT","FTFUUFFUT","TFFFTFFTT","FUTUUTFFT","FFTUTUFFT","TUTTTFFTT","TUTTUTTFT","TFTFTTTUT","FTFUTTTTT","FUFUTUTUT","FUTTFTFUT","FFTFUTTUT","TTTTUTFTT","TUTTUTFFT","TTFFFUTFT","TTFTTUTUT","FUTTTTFUT","TUFUUTTTT","FFTTTTTUT","TUTUUTTUT","FUTTUTFTT","TTFFFUFTT","TFTUFFFUT","FFTUUTFFT","FUTTTTFFT","TUTFUTTUT","TTFTUTTFT","FTTUTTTUT","TTTTUTTFT","FTTTUTTUT","TFTTUTFFT","FFTFUFTUT","FTFTTTTUT","TUFFUUFUT","TFFUFTTTT","TTFTUUFUT","FFTUUTTUT","TTFTTUFFT","TTTTUTFFT","TTTTTTTUT","TUTFUTTFT","TFTFTFTFT","TTFFUTFTT","TTFUUTTFT","TFFTUFFFT","TFFTUFTFT","TTFFUFFTT","FTTTFTFUT","FUTTUFTTT","TFFFUFTUT","FFFUUFFFT","FTFTTUFFT","TUTUUUTTT","FTFUUTTFT","TUFFUFFTT","TFTTFUTUT","FTTUFTTFT","FFFTTTTFT","FFFFUFTUT","FFFUFTTFT","TTTUUTTFT","TFFFUUFUT","FFFTTFFUT","TFFFTTFTT","TUFTUTFUT","TFTUTFTTT","FTTUUUTTT","FFFTFFFUT","FFFFTFFUT","TFFTUFTUT","FUTUTFFUT","FTTTUUFFT","TFFTTFFUT","FTFUFTTUT","TFFTUFFUT","FFFTUFTUT","TUTTTFTTT",
"FUFUUTTTT","FUTFTUFUT","TTFFUUTFT","FFFTUFFTT","FFFTFTFUT","TFTFUTTUT","FFFUFFFTT","FFFUTFFUT","FTTFTFFTT","FFFUTFFFT","TFFUUFFUT","FTFTTFFUT","TTFUUFFUT","TFTTTUTUT","TFFFUFTFT","TUFFUFFUT","FUFUUFFTT","FTFUUFFTT","FUFFTFFUT","FUFTFFFUT","TUTUUFTFT","TTTTTFFUT","FFFTUUTTT","FUFUUFFUT","TTFTUFFUT","TUFFTFTUT","FUFFTFFFT","TTFTUFTFT","TTTFFFTUT","FTFTUFFUT","TUFFFFFUT","FTFTFTTTT","FUFUTTFFT","TFTFFFFFT","TUTUUUTUT","FTTFFUFFT","TUTTFTFTT","TUFTFFFFT","FTFTTUFTT","TUFFFTFFT","FTTFUUFUT","FUFTTTFFT","FFTTTUFFT","FTFUTUFFT","TFFUUFTFT","TFTFFFTFT","TUTTUFFFT","FFFUUTFFT","TTFUFFTUT","TFTTUFFFT","TTTUFUFFT","FFFTUUFFT","TUTFFFFFT","FFTTFFTUT","TFFFFTTUT","FUFTTFTUT","TUTFFFFTT","TUFFTTTFT","FUTFUTTTT","TTTUUUTUT","FFFFUUTTT","TFTFUFTUT","FUFUUFTUT","FTTFUFFFT","FTFFFFFFT","FUFFFTTFT","FFFUFTFUT","FUFTTTTUT","TTTUUUFUT","TTFTFUFFT","FTTUUUTUT","FUTTUFTUT","TFFUTTFTT","TFFTUUFFT","FUFTTUFFT","FTTTTTFFT","TUFUFFFUT","FUFUFTTTT","TTFUFFFTT","TUTTFFTUT","TTFTUTTUT","TFTFUFFFT","TFTFUTFTT","FFTFTFTFT","FUFTFUFUT","TFTTUFTFT","FUFTUUFTT","TFTFUUTUT","FTTTTUTFT","FUTTTUFUT","FTFFFUFFT","FUFTUFTUT","TFTFFFTUT","TFFTFUFTT","TTTUFUFTT","TFTTUUTUT","FUFUTFFFT","FUFTUUFFT","FUFUFFTTT","FUFUFUTUT",
"FFTUFUFFT","FTFTUTFFT","TFTFTTFUT","FTFTFUFUT","TFTFUFTFT","FFTTFTFFT","TTTFUFTUT","TTFTFFFTT","FUFUTFFUT","FTFFUFFTT","FUTFFUTUT","TTFUUTFFT","FTTTTUFFT","TFTTFTTFT","FUTFUUFTT","FUTUFFFFT","FFTFTTFTT","FUTUFUFFT","TTTTUFTUT","FUTTFUTUT","FTTTFUFTT","FUFFTTTFT","FTTUTTTTT","TTTFFUFFT","TUTTUUFFT","TUTUUUFFT","FUFTUFFUT","TTFTUFTUT","FTFTUUFUT","FUFTTFFFT","TFTFFUTUT","TTTFUUFFT","FTFFUFTUT","TUFTTTFFT","FTTTFUTUT","TTFUUUFUT","FUFTFFTUT","FTTTFUFUT","FUTTFTFTT","TTFFUFFFT","TTFFUFTFT","FTFUTTFFT","FUFUUFFFT","TUFTUUFFT","TTFUFUFUT","TFFFUUTUT","TUTUFUFFT","TUTTTUFFT","TUTTUFTUT","FUTFFUFFT","TTTUUFFFT","FFFFUTTUT","TTTUFFFFT","FTFFUFFFT","FTTUTFTUT","TUTUTTTTT","FFTFFUTUT","TTFTFFTFT","FUTFTTFUT","FTTUFUFUT","FTFTFUTUT","FTFUFFTFT","TTFTUUTUT","TUTFUTFUT","TUFFFUFUT","FUFFUFFTT","FTTTTUTUT","TTFFTUTTT","TFFTUTFTT","TUFTUFFFT","TUTTFUTTT","TUFUFFTUT","FTFUUUFTT","FUTFUFTUT","FTTFTFFUT","FFTUTFFUT","FTFTUFFTT","TFFUUTFFT","TFTUFUFFT","FUTUUUFFT","FTFFTTFUT","TUTTFUFFT","TTTFTFTFT","FUFUFTFTT","TUTUTFTFT","TTFUTUFFT","FTTTFFTUT","FTTTUFFFT","TUTUFTFUT","TUFFTFFTT","FFFUTTFFT","FUTUTUTTT","FFTTUUFFT","TUTUFFFFT","TTTTFUTUT","FFTTUFFFT","TUFUUUFFT","TUTUUFFFT","FFFUTTTTT","FTTFUFTUT",
"TFFTFUFFT","FFFFFUTUT","TFTUTTFTT","TTFUUUTUT","FUFTFUTUT","FTFTFUTFT","FFTUFTFUT","TTTUTUFTT","TUFTUFTFT","TFTUTFFFT","FFTUUFTUT","TUFUUUTUT","FTTTFUFFT","TUFFUFTUT","FFFUTUTUT","TUFTFUFUT","TFTUUFFFT","TUFFUTFUT","TTFUUFTUT","TTFUFUFFT","FTTTFUTTT","TFFUFUFFT","FTFUFUTUT","TTTUUFTUT","TFFTFTTTT","FTTUTUFFT","FUFTTTFTT","FTFUFUFUT","FUFFTTFUT","FFTUFUTUT","TUFFTFFUT","TFFUTFTUT","TUFUTTFFT","FFFTTTTUT","FFTTTTTTT","TUTUUUFUT","TTFUTFFTT","FTFUTFFFT","TTTUUUTTT","TTFTUTFFT","FUTTTFTUT","FTTUUFTUT","TTFUUUFFT","FTFUFUFFT","TUTTFFFFT","FTFUUFTUT","TTTUTFTFT","FTTUFFTFT","FUFTFFFFT","FFFFFTTUT","FTTTTUFUT","FTTTUTTFT","TFTFFUFUT","TUTTTFTFT","TTTUFTTFT","TFFFUTTUT","TUFTUFFTT","TTFTFUTTT","FUTTFTTTT","TTFTFFFUT","TUFTUFFUT","TTTUTFFTT","TUTTFTFUT","TTTFTUTUT","TUTFUFTTT","TFTUFTTFT","FTTFUTTTT","FUFUTUFFT","TFTTFTFUT","TUFFFUTTT","TUFFUTTTT","TTFTFTTTT","TUFUUTFFT","TFFUFFFTT","TTTTFUFTT","TUFFUTFFT","FFTFTUTTT","TFFTFFFUT","TUFUFUTTT","TTFUUTFTT","TTFTFUFUT","TUTUFUFUT","TFFTTTFUT","TUTFUTFTT","TTTFFUFUT","FTTTUTTTT","FUFUUTFFT","FFFUUTFTT","TUTUFFTFT","TTFTUFFTT","TTFUFUTUT","TUFUFUFFT","TFFFUFFTT","TTFUFTTUT","TUTUUFFUT","TUTFUFFUT","FFTTFFFFT","TTTUUTFTT","TTFUUUTFT","TUFTFUTTT",
"TFFUTFTFT","TFTTUUFUT","TUTTFUTUT","TFFUUFFFT","FTTUUFFFT","TUFFFUFFT","FUTFFFFFT","FTTFFFTUT","TFFUFFTFT","TUFTFFTUT","TFTTFTFTT","TUFTFUFFT","TTTFFUTUT","TTFTUTFTT","TUFUFUTUT","FFFFUFFTT","TUFFUTFTT","FUTFTFFUT","FUTFTTFTT","TUFUFUFUT","TUFTUTTTT","TTTTFTFUT","TUFTUUFUT","TUTUUTFTT","FFTUFUFUT","FUFFFTFUT","FFFFTFFFT","TTTTUFFFT","FUFUFFFTT","TUTFUFFFT","TUFUUTTUT","FUFFTTTUT","TUFTTTTUT","TUFTUUFTT","FUTUUFFUT","TUTTTFTUT","TTTUTUTUT","FTFFTUFUT","TUTUTFTUT","TTFUTUTUT","FUTTFFFTT","TUFUTTTUT","FTFFTTFFT","FFTFUFFUT","FTTUTTFTT","FUTFTUTTT","FUFFFUFTT","TUTTTTFTT","TFFTTUFFT","FUTUTFTTT","FFFFUFTFT","FUTTTUTTT","FUFFUFTUT","FUFFFUTUT","FUTTTTTFT","FFFUUUFTT","TUFUUUFUT","FUTFUTTFT","TTFUFTFFT","FUFUUUTFT","FFFTTUFFT","FFFTUTFTT","TUTTTUFUT","FFFTFFTUT","TUFTUTTUT","TTTUTUTFT","TTTUUUFTT","TFTUFFFFT","TUTUUUFTT","FUFUFUFTT","FFFUFUTFT","FUFFFFTFT","FUFUUFTFT","TUTTUUTFT","FFFFUUTFT","FFFTUTTUT","FFFFTUTTT","TUTUUUTFT","FUFFUUTUT","TUTUTUTFT","TFTUUTFFT","FFFUUUTFT","FUTTUTTFT","FFFFFUTFT","FUFTFTTTT","TUTTTTTFT","TTTTFFFTT","TTTTTUTFT","TFFFFUTUT","TUTTTUTFT","TUTFUFTFT","FUFFUUFTT","TFTTUTTUT","TUTTUUFUT","FTTFTUFUT","TTTUUUTFT","TFFFFFFFT","FUTTTUTUT","FUTTUUTUT","FFFTUFFUT",
"TTFUTTFTT","TUFTTTFTT","FFTTUTTUT","TUTTUTFUT","TFFUFUFUT","TFFTTTFTT","TTFTTUFTT","TUFUTUFTT","TFTUFFTFT","FTFUFTFFT","FUTFFTFUT","TTFUTUFTT","FFFUUUFFT","TUFTTUFTT","TUTFFTFTT","TUTFFTTFT","TUTTFFTFT","TFTUTUFFT","TFTUTTTFT","TUTUFTFTT","TFTUUTFTT","TTFUTUTFT","TUTUTFFUT","TUFTTFTFT","FFFUTTFTT","TTFFUUFTT","TFFUFTTUT","TUFUTTTFT","TUFTTFFTT","FFTTTUTTT","FFFFUFFUT","TUTTTFFFT","TUFTTTTFT","TUFUTFFTT","FUTTFUFFT","FTFFUUFTT","FTFFUUTUT","FUTFFTTUT","TTFFFUFUT","FUTUUFTUT","TTTFUFTFT","TUFFTUFFT","FFFUTTTFT","TTTUUFTFT","TUFUFFFTT","FTFFFUFUT","TUFUFTTUT","TUTFTTFTT","TFTTUFTUT","TTFUUFFFT","FUTFUUTUT","FFFFTUFTT","TFFUUTTFT","TTTUUFTTT","TUTTFTTFT","TFFTTUTUT","TUFTFTTFT","FUTFFFFTT","TTTTUFFTT","TUTFFFFUT","FUTFUTTUT","FUFTFFFTT","TFTTUFFTT","FUFUFTTUT","FTFFUTFTT","TUFFFTTUT","FUTFUFTFT","FTFFTFFUT","FTFUUTTUT","TTFUUFTFT","FUTTUFFUT","TUFFUUTUT","TFFTTFTUT","FUTFFTTFT","TFFTTUTTT","FUTTTFFFT","TUFTFFFTT","FFFFTTTUT","FUTFTFFFT","TUFTTFFUT","TUTFTFTTT","FUTTTFTFT","FTFUUUTFT","TUFFFTTTT","FFTTUFTUT","TFTTFUFUT","TUFFTUTUT","FTFFFUTUT","TUTTTUFTT","FTTFFFFFT","TUFTFTFFT","FUTFTFFTT","TTTFTTTTT","FTFUFFFTT","FUTFTFTFT","TUFUFTFUT","FTFFFTTFT","FUTTFTTFT","FUTUTFFFT","FUFUTTTUT",
"TUTUFUFTT","FTTTFTTFT","FUFTFTTUT","FTTFUFFTT","FTFUUUTUT","TUTUTUFFT","FTFUUFTFT","FUFUTFTUT","FFFUUFFTT","FUTTTFFTT","TTTFUUFTT","TUTFTFFTT","TUFFFFTUT","TTFUUUFTT","FUFTFTTFT","TUTFTFFFT","FUTTFFTUT","FFTUUFFUT","FUTUTFTUT","FUFFTTFTT","TUTFFFTFT","FFFUFUFUT","TTTTUUTUT","TUFFFFFTT","FUFTTTTFT","FFFUUTTUT","FUFFFTTUT","FUFTFTFTT","FUTUUFFFT","FUTFUFTTT","TUFFUUFTT","TTFFTUFTT","TFTTTFFFT","TUFTTUTFT","TUFFTUFTT","FTFTUUTFT","FUTTUUTFT","FUFUUTTFT","TTTUUFFUT","TUFTFFTFT","TUFUUUFTT","TUTUTFTTT","FUTTUFFTT","TTFFTUTFT","FFFTUTTFT","FFTFUFFTT","FTTFTUTUT","FUTUUUFTT","FFFFUFFFT","FTFTFUFFT","FFTFUTTFT","TUFFUTTFT","FUFUUTTUT","TTTFUFFUT","TUFUUUTFT","FUTFTTTUT","FFFTUFTFT","FUTUUTTFT","TUFFUUTFT","FFFFFUFFT","FUFTUTTFT","TFTUFUTUT","TUTTUFFTT","FFTTUTFTT","TUTFTFTUT","TTTFTFTUT","FFFUTUFFT","TTFFUUTUT","FTFFUTTUT","FUTUFFTFT","TUTUUFFTT","TUFUUTTFT","TTFTUUFTT","TTFTTFTTT","TFFUUUFTT","TFTUFUTTT","FFFTUTTTT","TTTTTTFTT","TFFUUTTUT","FFTFFTFTT","FFFUFTFTT","TFTUUFFTT","FFTUFFFTT","TFFUUUTFT","FTTTUUFTT","TFTUTFTFT","FTFUFTFTT","TFTTUFFUT","FFFUFUFTT","FTTUUTTFT","FFTUUFTFT","FUFTFFTTT","FFTUUFFTT","TFFFFTFFT","TFTUUFTFT","TFTUUUFTT","FTTUUFTFT","FUFFUTTUT","FTFFTUTFT","FFTUFFTFT",
"TTTTUUFTT","FFFUUTTFT","FFTTTTFTT","FTTUFFFTT","TUTTUFFUT","FTFUFTTFT","TTTTUFFUT","FTTTTFFUT","TFTTTFFUT","FTTFUFTFT","FTTFUTTFT","FTTUUFFTT","FUTFFTFFT","FTTUUUFTT","FUTFTUFTT","FTTFTUFTT","FTFFTTTUT","FTTUTUFTT","TUTTTUTUT","TUTUTTTFT","FUTFTUTUT","TTTUFTTUT","FTTFTUTFT","TUFFFTTFT","FFTUTUFUT","FFTUTTFUT","TFTUTUTFT","FUFUTTFTT","FUTUTUTFT","TTTTTFTUT","FUFUTTTFT","FFFTFFTTT","FUFUTFFTT","FTFUTTTUT","FTFTFFFTT","TUFUFTTTT","FTFTUTTFT","FUFFTFTUT","TTTUUTTTT","FFTFTFTUT","FFTFTUTFT","FUTUFUTUT","FTTFUUFTT","FUTFUUTFT","FFTUTFTFT"
};

char cc[4];

int main() {
    int i;
    set<string> ret;
    for (i = 0 ; i < 1944; ++i) {
        ret.insert(string(ss[i]));
    }

    int Q;
    scanf("%d", &Q);
    while (Q-- > 0) {
        string ss = "";
        for (i = 0 ; i < 3; ++i) {
            for (int j = 0 ; j < 3; ++j) {
                scanf("%s", cc);
                ss += cc[0];
            }
        }

        if (ret.find(ss) != ret.end()) {
            printf("definable\n");
        } else {
            printf("undefinable\n");
        }
    }
    return 0;
}